const createUser = () => {
  return `
    CREATE TABLE IF NOT EXISTS
      users(
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR(128),
        password VARCHAR(128) NOT NULL,
        organization_name VARCHAR(128) NOT NULL UNIQUE
      )
  `;
};

const createClientLimit = () => {
  return `
    CREATE TABLE IF NOT EXISTS
      clients(
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_id VARCHAR(128),
        partner_id int,
        total_limit numeric DEFAULT 0
      )
  `;
};

const createOperation = () => {
  return `
  CREATE TABLE IF NOT EXISTS
    operations(
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      client_id VARCHAR(128),
      partner_id int,
      oper_type VARCHAR(128),
      oper_status VARCHAR(128),
      req_time TIMESTAMP,
      fault_sum numeric
    )
  `;
}


module.exports = {
  createUserTable: createUser,
  createClientLimitTable: createClientLimit,
  createOperationTable: createOperation,
};
