const createUser = () => {
  return `
    CREATE TABLE IF NOT EXISTS
      users(
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR(128),
        password VARCHAR(128) NOT NULL,
        organization_name VARCHAR(128) NOT NULL
      )
  `;
}


module.exports = {
  createUserTable: createUser,
}
